server:
  port: 10032
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 102400KB
      max-request-size: 102400KB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://pradar.host.mysql.amdb:3306/amdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:generator/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

influx:
  openurl: http://pradar.host.influxdb:8086
  username: root
  password: root
  database: pradar

zookeeper:
  server: pradar.host.zk01:2181,pradar.host.zk02:2181,pradar.host.zk03:2181

config:
  clickhouse:
    url: jdbc:clickhouse://pradar.host.clickhouse01:8123,pradar.host.clickhouse02:8123/default
    userName: default
    password: rU4zGjA/
    enableRound: true
  adaptor:
    instance:
      open: true